# Generated by Django 3.2.19 on 2023-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=4, max_digits=4)),
                ('quantite', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photosArticle')),
            ],
        ),
    ]
