# Generated by Django 3.2.19 on 2023-08-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0002_pannier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannier',
            name='compte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clientpage.compte'),
        ),
    ]
