# Generated by Django 3.2.19 on 2023-08-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20230810_1319'),
        ('clientpage', '0003_alter_pannier_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pannier',
            name='articleid',
        ),
        migrations.AddField(
            model_name='pannier',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.article'),
        ),
    ]
