# Generated by Django 3.2.19 on 2023-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0005_alter_pannier_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pannier',
            name='article',
        ),
        migrations.AddField(
            model_name='pannier',
            name='articleid',
            field=models.IntegerField(default=5),
        ),
    ]
